echo "Removing everything that generated by YunTable, and includes it's binary"
rm -r tablet*/ 
rm wal.log
rm yuncli
rm startMaster
rm startRegion
rm yfileTest
rm confTest
rm itemTest
rm listTest
rm utilTest
rm rpcTest
rm master.log
rm region.log
rm test.log
rm test.yfile
rm test

echo "Replacing the current conf file with the conf templates"
cp conf/cli.conf.template conf/cli.conf
cp conf/master.conf.template conf/master.conf
cp conf/region.conf.template conf/region.conf
